### PR TITLE
feat: add search.artsmia.org

### PR DESCRIPTION
**Pull request by kjell**
Add results from the Minneapolis Institute of Art

### CODE REVIEW

**Comment by chasemccoy** [comment]
@kjell This is awesome, thank you so much! You should be able to test it at: https://deploy-preview-1--museo-app.netlify.app/

Would you mind adding a link to the Minneapolis Institute of Art website into the header of the site as well?

**Comment by kjell** [comment]
Can do.

I also had to fix a few things to get it running locally - `npm install precinct` got me past an error spinning up `netlify dev` and I modified the `api/:source`s that require secret tokens to return an empty set of results (`[]`) when the token isn't available. Should I include those in this PR or keep them separate?

**Comment by chasemccoy** [comment]
Feel free to include them!

**Review by chasemccoy — APPROVED** [review]

**Comment by kjell** [comment]
I've been meaning to build basically this exact thing for a while, so I was super excited to see the same idea is already out there.

**Comment by chasemccoy** [comment]
It's long been on my wish list as well. Thank you for your help!

**Pull request merged**
